### ISSUE TITLE
IndexOutOfRangeException due to unrecognized DNS record type

### ISSUE THREAD

**Issue by TCGV** [DarekDan/Bdev.Net.Dns#2]
Hi,

I was testing this project and found that there is a bug in the ResourceRecord constructor.

The constructor signature is as follows:

```
internal ResourceRecord(Pointer pointer)
```

And within it there is a switch statement:

```
switch (_dnsType)
{
    case DnsType.NS:
        _record = new NSRecord(pointer);
        break;
    case DnsType.MX:
        _record = new MXRecord(pointer);
        break;
    case DnsType.ANAME:
        _record = new ANameRecord(pointer);
        break;
    case DnsType.SOA:
        _record = new SoaRecord(pointer);
        break;
    default:
    {
        // move the pointer over this unrecognised record
        pointer += recordLength;
        break;
    }
}
```

So when an unrecognized record type is received (ex: AAAA record) the implicit sum operator is executed, and assigns a new object to the `pointer` variable, instead of increasing the position of the original `pointer` variable.

The fix is really simple, juste define the following method in the `Pointer` class:

```
public void Seek(int offset)
{
    _position += offset;
}
```

And replace `pointer += recordLength;` by `pointer.Seek(recordLength)`.

Regards,
Thomas Vilhena

**Comment by DarekDan** [comment]
Thank you for the fix. Resolved in version 1.0.4.
