### ISSUE TITLE
TXT record with multiple lines doesn't return properly

### ISSUE THREAD

**Issue by PaulFarry** [DarekDan/Bdev.Net.Dns#4]
I created the following TXT record in azure DNS.

```
item1:value
item2:value
```

when I query this TXT record with the library i get
```
item1:value
```

when I use 

```
C:\>nslookup
Default Server:  192-168-1-1.tpgi.com.au
Address:  192.168.1.1

> set type=txt
> configuration-development.<somedomain>.com
Server:  192-168-1-1.tpgi.com.au
Address:  192.168.1.1

Non-authoritative answer:
configuration-development.<somedomain>.com        text =

        "item1:value"
        "item2:value"
```

**Comment by DarekDan** [comment]
I will look into it.

Darek

On May 12, 2020, at 6:08 PM, Paul Farry <notifications@github.com> wrote:

﻿

I created the following TXT record in azure DNS.

item1:value
item2:value


when I query this TXT record with the library i get

item1:value


when I use

C:\>nslookup
Default Server:  192-168-1-1.tpgi.com.au
Address:  192.168.1.1

> set type=txt
> configuration-development.<somedomain>.com
Server:  192-168-1-1.tpgi.com.au
Address:  192.168.1.1

Non-authoritative answer:
configuration-development.<somedomain>.com        text =

        "item1:value"
        "item2:value"

**Comment by DarekDan** [comment]
I am not sure you have a valid test case. For example, if I run it against the google.com I do receive five distinct results.


▶ | [0] | {globalsign-smime-dv=CDYX+XFHUw2wml6/Gb8+59BsH31KzUr6c1l2BPvqKX8=} | Bdev.Net.Dns.TXTRecord
▶ | [1] | {facebook-domain-verification=22rm551cu4k0ab0bxsw536tlds4h95} | Bdev.Net.Dns.TXTRecord
▶ | [2] | {docusign=05958488-4752-4ef2-95eb-aa7ba8a3bd0e} | Bdev.Net.Dns.TXTRecord
▶ | [3] | {docusign=1b0a6754-49b1-4db5-8540-d2c12664b289} | Bdev.Net.Dns.TXTRecord
▶ | [4] | {v=spf1 include:_spf.google.com ~all} | Bdev.Net.Dns.TXTRecord

Sample code:

```
var request = new Request {RecursionDesired = true}.WithQuestion(new Question("google.com", DnsType.TXT));
var result = Resolver.Lookup(request);
var l= result.Answers.Select(s => s.Record).OfType<TXTRecord>().ToList();
```

**Comment by markvantilburg** [comment]
If you check crmMonitor.nl you will see that bigger txt records do not work. After adding the fixes from pull 5 and 6 this works. This is an edge case but a customer also has multiple txt records that triggers this bug.

I think microsoft.com would also trigger this bug.
