### ISSUE TITLE
Test run doesn't pass.

### ISSUE THREAD

**Issue by mittnav** [DarekDan/Bdev.Net.Dns#8]
This library was a favorite 10 years ago (have an old zip file from those days), and I'm glad I now found it on NuGet and GitHub.

Is it expected that the tests will run without errors?
Doesn't work for me...
![image](https://user-images.githubusercontent.com/109823249/188182334-4a9a2a39-536a-4dde-9223-bd2d4533bd37.png)

**Comment by DarekDan** [comment]
What errors are you getting?

**Comment by mittnav** [comment]
If I follow `CNameRecordMustExist` I get to `Parallel.ForEach(IP4, server =>` without any problems, but somewhere inside that method something must go wrong because `return bag.Cast<T>()`, here bag is empty and an exception is later thrown:
![image](https://user-images.githubusercontent.com/109823249/188200671-a066c1ed-38b6-4cad-a1c3-ce2ff231c05f.png)

The other errors are kind of the same behavior.

**Comment by DarekDan** [comment]
Indeed. Format change in DNS responses is causing it. I will have to investigate.

**Comment by mittnav** [comment]
Ok, changes are never pleasant...

I've tried to find an error but it's a little difficult to follow all paths when one isn't so skilled at this subject.

However fine to know it isn't my configuration.

Thanks for the quick response.

**Comment by DarekDan** [comment]
Resolved in 1.0.13. Being published. Thank you for bringing it to my attention.

**Comment by mittnav** [comment]
Excellent... it was quick work...

**Comment by mittnav** [comment]
Perhaps I jumped to a premature conclusion or maybe I've got something wrong with my configuration after all.

Two of the problems have been resolved by the fix; the other two still remains.

When I run `CompareTwoRecords` I get stuck on:

![image](https://user-images.githubusercontent.com/109823249/188248148-7070cc25-fd68-4520-b1a3-5e863c37501a.png)

###### It's getting late for me, nearly 3 o'clock, I will investigate more another day.

###### Have a nice weekend.

**Comment by DarekDan** [comment]
I've expanded the test case for you. Let me know if any fails in particular.
![2022-09-02 22_14_46-Bdev Net Dns - Microsoft Visual Studio](https://user-images.githubusercontent.com/5083576/188252116-b2e601a8-08bd-47ba-96e1-296662699b1c.png)

**Comment by mittnav** [comment]
Thanks for your dedication.

Pretty interesting but I can't really see the pattern.
Could it have to do with _real_ versus _fake_ addresses or what are the differences due to...
![image](https://user-images.githubusercontent.com/109823249/188253984-0e37da0a-a0c3-40b2-81a9-99140638d830.png)

**Comment by DarekDan** [comment]
It looks like some of the DNS server addresses are being actively blocked. All the IPs included in the test are valid, high performance, public DNS servers. One of your firewalls might be blocking them, with UDP and TCP rules.

**Comment by DarekDan** [comment]
If you have WSL, you could test one of them with 'nc -vz 1.1.1.1 53'.

**Comment by mittnav** [comment]
The same idea applies to me.
Haven't had time to follow up on that. (Are all addresses real existing DNS servers?)

Now the question becomes, how should this be handled, is it right to throw an exception or should it be handled in a more compassionate way?

But I suppose it's the right thing to do, you then have to deal with it in the code.

**Comment by DarekDan** [comment]
At such low level, I think it should. However, I am not advocating for flow control using exceptions. 

Perhaps in the future a return type of Result will be implemented. Lots of discussions in the industry about it.

**Comment by DarekDan** [comment]
Check this out: https://betterprogramming.pub/how-and-where-to-handle-exceptions-while-maintaining-a-great-api-e3df6c084746

I might implement something like it in the future.

**Comment by mittnav** [comment]
Thanks for your reply.

My last message was as you understand a reply to a previous post, our messages got a little out of sync.

I had already checked the DNS lookup with 1.1.1.1 and that's right, it gets timed out (blocked). However, I don't remember now when I would have created these rules, but in the past, I was trying to prevent advertising, etc. in many various ways (actually, I worked as CCNA once upon a time, but it's been a long time since now, don't remember much...).

Thanks for the article.
TryGet...() with bool I often use myself but this is a step further...

**The good thing is that I now know why tests fail and then can handle them accordingly.**

**Comment by DarekDan** [comment]
And food for thought ... just use the default DNS server methods if you don't have to specify a server.

**Comment by mittnav** [comment]
Yes, that part is no problem, thank you.

My issue was if I could trust the tests or not (in the event of me trying to do some experiment with the code).

**Comment by mittnav** [comment]
_I'll mention this here, a bit off the record, instead of in the PR:_

As I mentioned, I'm going to experiment a bit with the code and I start with the most important(!?) part, updating to the new modern SDK style.

The next step will be to change some statements to a later C# style, thinking among other things on new(), in some cases string interpolation where it's missing, in those cases using() spans an entire method change to simple using() and also implicit/global using.

I can see that you are not allergic to expression body so there may be a few more of those, and last but not least try to go through nullable statements.

I know you could do all this yourself but sometimes one doesn't have the time or it just doesn't happen...

Will send a few PRs later, possibly they will be cumulative (it will take too long time to go through a whole PR/merge chain for each change), in which case you will have to go through the commits in turn.

**_I won't be the least bit upset or offended if you don't want these changes, just deny them._**

Also, I don't in any way at all imply that there is something wrong with your code, on the contrary, it's purely selfish reasons because it will be simpler for me to understand what the code does.
